### ISSUE TITLE
Analagous

### ISSUE THREAD

**Issue by spdaly** [infusion/jQuery-xcolor#7]
I'm trying us use the analogous method to get a set of colors for SVG fills.  The code is below.  The array that is returned has all the same colors.

    var colors = [];
    colors = $.xcolor.analogous('#5c5c5c', $('polygon').length);
    $('polygon').each(function(index){
        console.log(colors[index].getHex());
        $(this).attr('fill', colors[index].getHex());
    })

**Comment by infusion** [comment]
Hi,

this isn't a bug or a problem of the library, this is how analogous colors are defined. Analogous colors just rotate the hue wheel and as #5c5c5c doesn't have any saturation, the result is always the same gray scale color. If you have suggestions on how to make reasonable analogous colors with no saturation, they're more than welcome.

Here is a little online tool, which confirms this:
http://www.rapidtables.com/convert/color/hsv-to-rgb.htm

Robert

**Comment by spdaly** [comment]
@infusion 
I realized and confirmed this yesterday.  I obviously need to spend some time learning some basic color theory.

Thanks for the help.
