### ISSUE TITLE
NPM Repo

### ISSUE THREAD

**Issue by KnightYoshi** [infusion/jQuery-xcolor#8]
Care to put this on the NPM repo as well?

**Comment by infusion** [comment]
I made a complete rewrite of xcolor, which also comes with a npm package. I developed this package completely test driven, but I need some time to add more test cases and fix bugs. How urgent do you need it? I then can change my release schedule.

**Comment by Knight-Yoshi** [comment]
Not _terribly_ urgent, but it's highly desired. We use npm packages for as many of our dependencies as possible. This is a great library, I'd rather you iron things out more though. :)

**Comment by infusion** [comment]
Okay, I'll see if I can make in the next 3 weeks :)

**Comment by Knight-Yoshi** [comment]
Just checking in.

Any progress for the node package?

**Comment by yxliang01** [comment]
Hmm it's almost a year since the last comment. Any progress? I would really appreciate that if this can be published as a npm package.

**Comment by KnightYoshi** [comment]
@infusion Anything?
