### ISSUE TITLE
Improving the Docs

### ISSUE THREAD

**Issue by KnightYoshi** [infusion/jQuery-xcolor#9]
So can there be some clarification in the docs about the method parameters?
For instance darken and lighten, `$.xcolor.darken(color[, step=1[, shade=32]])`
I understand what the color parameter is, but I'm not sure about step and shade and how the two relate to each other.

Another example is the greyfilter, `$.xcolor.greyfilter(color[, fomula=1])`
I have no idea what the 'formula' parameter is used for.

I'm not very good with color manipulation and understanding what it means. So just some clarification in the docs about these things would be much appreciated.

**Comment by VsevolodGolovanov** [comment]
Also the doc mentions `isReadable`, but it's just `readable` now.
